language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - "composer install --dev"
  - "composer require codeclimate/php-test-reporter --dev"

script:
  - "phpunit --coverage-text --coverage-clover build/logs/clover.xml"

addons:
  code_climate:
    repo_token: a49025aba6a313393c079c99ae42fff71e988cf60ead0022c6501166b1d7037a

after_success:
  - ./vendor/bin/test-reporter